## Tensor을 다루는 함수들

In [0]:
%matplotlib inline
import numpy as np
import tensorflow as tf 
import matplotlib.pyplot as plt
import pandas as pd

tf.enable_eager_execution()
np.set_printoptions(formatter={
    'float_kind': lambda x: "{0:0.3f}".format(x)})

## 예제 데이터 )  califonia housing price

MedInc : 행정 구역 내 소득의 중앙값<br>
HouseAge : 행정 구역 내 주택 연식의 중앙값<br>
AveRooms : 평균 방 갯수<br>
AveBedrms : 평균 침실 갯수<br>
Population : 행정 구역 내 인구 수<br>
AveOccup : 평균 자가 비율<br>
Latitude : 해당 행정 구역의 위도<br>
Longitude : 해당 행정 구역의 경도<br>

In [0]:
from sklearn.datasets import fetch_california_housing
california = fetch_california_housing()

clf_data = california.data

df = pd.DataFrame(california.data,columns=california.feature_names)
df.head()

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

## 문제 1. 평균 보다 큰 값의 갯수 세기

+ 각 열의 평균보다 큰 값의 갯수를 출력해 보세요. <br>

In [0]:
# 우선 실행해주세요
tf_data = tf.constant(df.values)
tf_data

<tf.Tensor: id=0, shape=(20640, 8), dtype=float64, numpy=
array([[8.325, 41.000, 6.984, ..., 2.556, 37.880, -122.230],
       [8.301, 21.000, 6.238, ..., 2.110, 37.860, -122.220],
       [7.257, 52.000, 8.288, ..., 2.802, 37.850, -122.240],
       ...,
       [1.700, 17.000, 5.206, ..., 2.326, 39.430, -121.220],
       [1.867, 18.000, 5.330, ..., 2.123, 39.430, -121.320],
       [2.389, 16.000, 5.255, ..., 2.617, 39.370, -121.240]])>

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer1`에 담아주세요

In [0]:
data1 = tf_data > tf.reduce_mean(tf_data, axis=0)
int_mask = tf.cast(data1, tf.int64)
answer1 = tf.reduce_sum(int_mask, axis = 0)


#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [0]:
from numpy.testing import assert_array_equal

assert 'answer1' in globals(), "결과를 answer1 변수에 담아주세요!, answer1 값을 보고 평가합니다."

A = df[df>df.mean()].count().values

if "numpy" in dir(answer1):
    answer1 = answer1.numpy()

assert_array_equal(A, answer1,"\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 2. HouseAge가 20년 이상의 데이터 가져오기

* HouseAge(2번째 열)가 20보다 크거나 같은 데이터들을 가져와 주세요

In [0]:
# 우선 실행해주세요
tf_data = tf.constant(df.values)
tf_data

<tf.Tensor: id=108, shape=(20640, 8), dtype=float64, numpy=
array([[8.325, 41.000, 6.984, ..., 2.556, 37.880, -122.230],
       [8.301, 21.000, 6.238, ..., 2.110, 37.860, -122.220],
       [7.257, 52.000, 8.288, ..., 2.802, 37.850, -122.240],
       ...,
       [1.700, 17.000, 5.206, ..., 2.326, 39.430, -121.220],
       [1.867, 18.000, 5.330, ..., 2.123, 39.430, -121.320],
       [2.389, 16.000, 5.255, ..., 2.617, 39.370, -121.240]])>

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer2`에 담아주세요

In [0]:
data1 =tf_data[:,1]
data2 = tf.where(data1 >= 20).numpy()
# answer2 = data2
answer2 = tf.gather_nd(tf_data, data2).numpy()

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [0]:
from numpy.testing import assert_array_equal

assert 'answer2' in globals(), "결과를 answer2 변수에 담아주세요!"

A = df[df.HouseAge>=20].values

if "numpy" in dir(answer2):
    answer2 = answer2.numpy()

assert_array_equal(A, answer2,
                   "\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 3. HouseAge가 50년 이상의 행 인덱스 가져오기
* HouseAge(2번째 열)가 50보다 크거나 같은 데이터의 인덱스를 가져와 주세요

In [0]:
# 우선 실행해주세요
tf_data = tf.constant(df.values)
tf_data

<tf.Tensor: id=209, shape=(20640, 8), dtype=float64, numpy=
array([[8.325, 41.000, 6.984, ..., 2.556, 37.880, -122.230],
       [8.301, 21.000, 6.238, ..., 2.110, 37.860, -122.220],
       [7.257, 52.000, 8.288, ..., 2.802, 37.850, -122.240],
       ...,
       [1.700, 17.000, 5.206, ..., 2.326, 39.430, -121.220],
       [1.867, 18.000, 5.330, ..., 2.123, 39.430, -121.320],
       [2.389, 16.000, 5.255, ..., 2.617, 39.370, -121.240]])>

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer3`에 담아주세요

In [0]:
# tf.where(tf_data>=50).numpy()

data1 =tf_data[:,1]
data2 = tf.where(data1 >= 50).numpy()
answer3 = data2
# tf.gather_nd(tf_data, data2).numpy()

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [0]:
from numpy.testing import assert_array_equal

assert 'answer3' in globals(), "결과를 answer3 변수에 담아주세요!"

A = np.where(df.HouseAge>=50)[0]

if "numpy" in dir(answer3):
    answer3 = answer3.numpy()

assert_array_equal(A, answer3.ravel(),
                   "\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!
